"""create tables

Revision ID: 468d20bb4ae7
Revises: 
Create Date: 2026-03-06 05:43:54.515496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '468d20bb4ae7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.execute("DO $$ BEGIN CREATE TYPE user_role AS ENUM('ADMIN', 'USER', 'MODERATOR', 'OWNER'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_uid', sa.UUID(), nullable=True),
    sa.Column('target_uid', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor_action', 'audit_log', ['actor_uid', 'action'], unique=False)
    op.create_index('ix_audit_created', 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_uid'), 'audit_log', ['actor_uid'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_request_id'), 'audit_log', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_log_target_uid'), 'audit_log', ['target_uid'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of the refresh token'),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_sessions_token_hash'), 'refresh_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_sessions_user_uid'), 'refresh_sessions', ['user_uid'], unique=False)
    op.create_index('ix_sessions_expires', 'refresh_sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_user_active', 'refresh_sessions', ['user_uid', 'is_revoked'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_token_blacklist_expires', 'token_blacklist', ['expires_at'], unique=False)
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.create_index(op.f('ix_token_blacklist_user_uid'), 'token_blacklist', ['user_uid'], unique=False)
    op.create_table('user_token_revocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('revoked_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_token_revocations_user_uid'), 'user_token_revocations', ['user_uid'], unique=True)
    op.create_table('users',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', postgresql.ENUM('ADMIN', 'USER', 'MODERATOR', 'OWNER', name='user_role', create_type=False), server_default='USER', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('totp_secret', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default='false', nullable=False, comment='Email confirmed via link'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_token_revocations_user_uid'), table_name='user_token_revocations')
    op.drop_table('user_token_revocations')
    op.drop_index(op.f('ix_token_blacklist_user_uid'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_index('ix_token_blacklist_expires', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index('ix_sessions_user_active', table_name='refresh_sessions')
    op.drop_index('ix_sessions_expires', table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_user_uid'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_token_hash'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_audit_log_target_uid'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_request_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_uid'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('ix_audit_created', table_name='audit_log')
    op.drop_index('ix_audit_actor_action', table_name='audit_log')
    op.drop_table('audit_log')
    postgresql.ENUM(name='user_role').drop(op.get_bind())
    # ### end Alembic commands ###
