from datetime import datetime
from typing import Protocol, runtime_checkable
from uuid import UUID

from src.core.constants import UserRole
from src.domain.entities import RefreshSession, TokenPayload, UserEntity


@runtime_checkable
class UserRepositoryProtocol(Protocol):
    async def get_by_id(self, uid: UUID) -> UserEntity | None: ...
    async def get_by_email(self, email: str) -> UserEntity | None: ...
    async def get_by_username(self, username: str) -> UserEntity | None: ...
    async def get_by_phone(self, phone: str) -> UserEntity | None: ...
    async def get_all(
        self, offset: int = 0, limit: int = 50,
    ) -> list[UserEntity]: ...
    async def count(self) -> int: ...
    async def create(self, user: UserEntity) -> UserEntity: ...
    async def update(self, user: UserEntity) -> UserEntity: ...
    async def delete(self, uid: UUID) -> None: ...
    async def exists_by_email(self, email: str) -> bool: ...
    async def exists_by_username(self, username: str) -> bool: ...
    async def exists_by_phone(self, phone: str) -> bool: ...


@runtime_checkable
class RefreshSessionRepositoryProtocol(Protocol):
    async def create(
        self, session: RefreshSession,
    ) -> RefreshSession: ...

    async def get_by_token_hash(
        self, token_hash: str,
    ) -> RefreshSession | None: ...

    async def revoke(self, token_hash: str) -> None: ...

    async def revoke_all_for_user(self, user_uid: UUID) -> int: ...

    async def get_active_sessions(
        self, user_uid: UUID,
    ) -> list[RefreshSession]: ...

    async def count_active_sessions(self, user_uid: UUID) -> int: ...

    async def mark_replaced(
        self, old_token_hash: str, new_token_hash: str,
    ) -> None: ...

    async def update_last_used(self, token_hash: str) -> None: ...

    async def cleanup_expired(self) -> int: ...

@runtime_checkable
class AuditLogProtocol(Protocol):
    async def log(
        self,
        action: str,
        actor_uid: UUID | None = None,
        target_uid: UUID | None = None,
        details: dict | None = None,
        ip_address: str | None = None,
        user_agent: str | None = None,
        request_id: str | None = None,
        success: bool = True,
    ) -> None: ...

    async def get_user_history(
        self, user_uid: UUID, offset: int = 0, limit: int = 50,
    ) -> list[dict]: ...

    async def get_by_action(
        self, action: str, offset: int = 0, limit: int = 50,
    ) -> list[dict]: ...

    async def get_all(
        self, offset: int = 0, limit: int = 50,
    ) -> list[dict]: ...

@runtime_checkable
class UnitOfWorkProtocol(Protocol):
    users: UserRepositoryProtocol
    refresh_sessions: RefreshSessionRepositoryProtocol
    audit: AuditLogProtocol

    async def __aenter__(self) -> "UnitOfWorkProtocol": ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


@runtime_checkable
class PasswordHasherProtocol(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, hash: str) -> bool: ...
    def needs_rehash(self, hash: str) -> bool: ...


@runtime_checkable
class TokenServiceProtocol(Protocol):
    def create_access_token(self, user: UserEntity) -> str: ...
    def decode_access_token(self, token: str) -> TokenPayload: ...


@runtime_checkable
class URLSafeTokenServiceProtocol(Protocol):
    def create_token(self, data: dict, purpose: str) -> str: ...
    def decode_token(
        self, token: str, purpose: str, max_age: int,
    ) -> dict: ...


@runtime_checkable
class TOTPServiceProtocol(Protocol):
    def generate_secret(self) -> str: ...
    def encrypt_secret(self, secret: str) -> str: ...
    def decrypt_secret(self, encrypted: str) -> str: ...
    def generate_uri(self, secret: str, email: str) -> str: ...
    def generate_qr_base64(self, uri: str) -> str: ...
    def verify_code(self, secret: str, code: str) -> bool: ...


@runtime_checkable
class EmailServiceProtocol(Protocol):
    async def send_confirmation_email(
        self, email: str, username: str, token: str,
    ) -> None: ...

    async def send_password_reset_email(
        self, email: str, username: str, token: str,
    ) -> None: ...


@runtime_checkable
class RateLimiterProtocol(Protocol):
    async def check_rate_limit(
        self, key: str, max_attempts: int, window_seconds: int,
    ) -> None: ...

    async def reset(self, key: str) -> None: ...

    async def get_remaining(
        self, key: str, max_attempts: int, window_seconds: int,
    ) -> tuple[int, int]: ...